import { useEffect, useState } from "react";
import { adminAuditDetail, adminListAudits, adminListMessages, adminListSessions, adminListTraces, adminTraceDetail, type AdminAudit, type AdminMessage, type AdminSession, type AdminTrace } from "../../api";
import { AdminButton, AdminInput, AdminNotice, AdminPage, AdminSelect, AdminTable, AdminTd, AdminTh } from "../../components/AdminTable";
import { JsonViewer } from "../../components/JsonViewer";

type Tab = "sessions" | "messages" | "traces" | "audits";
const sensitive = /token|credential|password|api[_-]?key|secret/i;
function safeJson(value: unknown): unknown { if (Array.isArray(value)) return value.map(safeJson); if (!value || typeof value !== "object") return value; return Object.fromEntries(Object.entries(value as Record<string, unknown>).filter(([key]) => !sensitive.test(key)).map(([key, item]) => [key, safeJson(item)])); }
function text(value: unknown) { return value === undefined || value === null ? "—" : String(value); }
export function AuditsPage() {
  const [tab, setTab] = useState<Tab>("sessions"); const [items, setItems] = useState<Array<AdminSession | AdminMessage | AdminTrace | AdminAudit>>([]); const [filters, setFilters] = useState({ q: "", status: "", owner_email: "", trace_id: "", tool_name: "", error_code: "", actor_email: "", type: "", actor: "", target: "" }); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [detail, setDetail] = useState<unknown>(null);
  useEffect(() => { let alive = true; setLoading(true); setError(""); setDetail(null); const run = tab === "sessions" ? adminListSessions({ q: filters.q, status: filters.status, owner_email: filters.owner_email, limit: 100 }) : tab === "messages" ? adminListMessages({ q: filters.q, status: filters.status, owner_email: filters.owner_email, limit: 100 }) : tab === "traces" ? adminListTraces({ trace_id: filters.trace_id, tool_name: filters.tool_name, error_code: filters.error_code, actor_email: filters.actor_email }) : adminListAudits({ type: filters.type, actor: filters.actor, target: filters.target, limit: 100 }); void run.then((result) => { if (alive) setItems(result.items || []); }).catch((e) => { if (alive) setError(e instanceof Error ? e.message : "审计数据加载失败"); }).finally(() => { if (alive) setLoading(false); }); return () => { alive = false; }; }, [tab, filters]);
  const set = (key: keyof typeof filters, value: string) => setFilters((old) => ({ ...old, [key]: value }));
  const showDetail = async (row: AdminSession | AdminMessage | AdminTrace | AdminAudit) => { try { setError(""); const traceId = typeof row.trace_id === "string" ? row.trace_id : ""; const id = typeof row.id === "string" ? row.id : ""; if (tab === "traces" && traceId) setDetail(await adminTraceDetail(traceId)); else if (tab === "audits" && id) setDetail(await adminAuditDetail(id)); else setDetail(row); } catch (e) { setError(e instanceof Error ? e.message : "详情加载失败"); } };
  const filterBox = tab === "traces" ? <><AdminInput placeholder="trace_id" value={filters.trace_id} onChange={(e) => set("trace_id", e.target.value)} /><AdminInput placeholder="tool_name" value={filters.tool_name} onChange={(e) => set("tool_name", e.target.value)} /><AdminInput placeholder="error_code" value={filters.error_code} onChange={(e) => set("error_code", e.target.value)} /><AdminInput placeholder="actor_email" value={filters.actor_email} onChange={(e) => set("actor_email", e.target.value)} /></> : tab === "audits" ? <><AdminInput placeholder="type/action" value={filters.type} onChange={(e) => set("type", e.target.value)} /><AdminInput placeholder="actor" value={filters.actor} onChange={(e) => set("actor", e.target.value)} /><AdminInput placeholder="target" value={filters.target} onChange={(e) => set("target", e.target.value)} /></> : <><AdminInput placeholder="关键词" value={filters.q} onChange={(e) => set("q", e.target.value)} /><AdminSelect value={filters.status} onChange={(e) => set("status", e.target.value)}><option value="">全部状态</option><option value="active">active</option><option value="completed">completed</option><option value="deleted">deleted</option></AdminSelect><AdminInput placeholder="owner_email" value={filters.owner_email} onChange={(e) => set("owner_email", e.target.value)} /></>;
  return <AdminPage title="审计与追溯" description="只读查看会话、消息、trace 和审计记录；敏感字段自动隐藏。"><div className="flex flex-wrap gap-2 border-b border-border">{(["sessions", "messages", "traces", "audits"] as Tab[]).map((value) => <button type="button" key={value} onClick={() => setTab(value)} className={`border-b-2 px-3 py-2 text-sm ${tab === value ? "border-primary font-medium text-primary" : "border-transparent text-muted-fg"}`}>{value}</button>)}</div><div className="flex flex-wrap gap-2 rounded-xl border border-border bg-card p-3 shadow-panel">{filterBox}</div>{error ? <AdminNotice>{error}</AdminNotice> : null}{loading ? <div className="rounded-xl border border-border bg-card p-8 text-center text-sm text-muted-fg">加载中…</div> : items.length === 0 ? <div className="rounded-xl border border-border bg-card p-8 text-center text-sm text-muted-fg">暂无记录</div> : <AdminTable><thead><tr>{tab === "traces" ? <><AdminTh>trace_id</AdminTh><AdminTh>tool_name</AdminTh><AdminTh>error_code</AdminTh><AdminTh>操作</AdminTh></> : tab === "audits" ? <><AdminTh>时间</AdminTh><AdminTh>actor</AdminTh><AdminTh>action</AdminTh><AdminTh>target</AdminTh><AdminTh>操作</AdminTh></> : <><AdminTh>ID</AdminTh><AdminTh>状态/标题</AdminTh><AdminTh>时间</AdminTh><AdminTh>操作</AdminTh></>}</tr></thead><tbody>{items.map((row, index) => <tr key={text(row.id || row.trace_id || index)}>{tab === "traces" ? <><AdminTd className="font-mono text-xs">{text(row.trace_id)}</AdminTd><AdminTd>{text(row.tool_name)}</AdminTd><AdminTd>{text(row.error_code)}</AdminTd><AdminTd><button type="button" onClick={() => void showDetail(row)} className="text-xs text-primary hover:underline">查看 events</button></AdminTd></> : tab === "audits" ? <><AdminTd className="text-xs">{text(row.created_at)}</AdminTd><AdminTd>{text(row.actor_email)}</AdminTd><AdminTd>{text(row.action)}</AdminTd><AdminTd>{text(row.target_type)} / {text(row.target_id)}</AdminTd><AdminTd><button type="button" onClick={() => void showDetail(row)} className="text-xs text-primary hover:underline">查看 detail</button></AdminTd></> : <><AdminTd className="font-mono text-xs">{text(row.id)}</AdminTd><AdminTd>{text(row.status || row.title || row.role)}</AdminTd><AdminTd className="text-xs">{text(row.created_at || row.updated_at)}</AdminTd><AdminTd><button type="button" onClick={() => void showDetail(row)} className="text-xs text-primary hover:underline">查看</button></AdminTd></>}</tr>)}</tbody></AdminTable>}{detail ? <div className="rounded-xl border border-border bg-card p-4 shadow-panel"><div className="mb-2 flex items-center justify-between"><h2 className="font-semibold">详情</h2><AdminButton variant="secondary" onClick={() => setDetail(null)}>关闭</AdminButton></div><JsonViewer value={safeJson(detail)} label={tab === "traces" ? "events JSON" : tab === "audits" ? "audit detail JSON" : "record JSON"} /></div> : null}</AdminPage>;
}
