import { useCallback, useEffect, useState } from "react";
import { adminGetConfig, adminPatchConfig } from "../../api";
import { AdminButton, AdminInput, AdminNotice, AdminPage, AdminTable, AdminTd, AdminTh, AdminTextarea } from "../../components/AdminTable";

const keys = ["retention.conversation_days", "retention.audit_days", "auth.email_whitelist_suffixes", "auth.login_fail_limit", "sandbox.max_concurrent", "sandbox.timeout_s", "llm.default_provider_id", "llm.default_model", "conversation.user_max_messages"] as const;
const integerRanges: Record<string, [number, number]> = { "sandbox.max_concurrent": [1, 32], "sandbox.timeout_s": [1, 300] };
function display(value: unknown) { return typeof value === "string" ? value : JSON.stringify(value); }
export function ConfigPage() {
  const [values, setValues] = useState<Record<string, unknown>>({}); const [drafts, setDrafts] = useState<Record<string, string>>({}); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(""); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const next = await adminGetConfig(); setValues(next); setDrafts(Object.fromEntries(keys.map((key) => [key, display(next[key])]))); } catch (e) { setError(e instanceof Error ? e.message : "系统配置加载失败"); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const save = async (key: string) => { setError(""); setSuccess(""); let value: unknown = drafts[key] ?? ""; try { if (integerRanges[key]) { const parsed = Number(value); const [min, max] = integerRanges[key]; if (!Number.isInteger(parsed) || parsed < min || parsed > max) throw new Error(`${key} 必须是 ${min}~${max} 的整数`); value = parsed; } else if (key !== "llm.default_model") value = JSON.parse(String(value)); setSaving(key); await adminPatchConfig(key, value); setSuccess(`${key} 已更新`); await load(); } catch (e) { setError(e instanceof Error ? e.message : "配置更新失败"); } finally { setSaving(""); } };
  return <AdminPage title="系统配置" description="只允许修改 T11 白名单中的 9 个热更新参数。">{error ? <AdminNotice>{error}</AdminNotice> : null}{success ? <AdminNotice kind="success">{success}</AdminNotice> : null}{loading ? <div className="rounded-xl border border-border bg-card p-8 text-center text-sm text-muted-fg">加载中…</div> : <AdminTable><thead><tr><AdminTh>Key</AdminTh><AdminTh>当前值</AdminTh><AdminTh>编辑</AdminTh><AdminTh>操作</AdminTh></tr></thead><tbody>{keys.map((key) => <tr key={key}><AdminTd className="whitespace-nowrap font-mono text-xs">{key}</AdminTd><AdminTd className="max-w-sm break-all text-xs">{display(values[key])}</AdminTd><AdminTd>{integerRanges[key] ? <AdminInput type="number" min={integerRanges[key][0]} max={integerRanges[key][1]} value={drafts[key] || ""} onChange={(e) => setDrafts({ ...drafts, [key]: e.target.value })} /> : <AdminTextarea rows={2} value={drafts[key] || ""} onChange={(e) => setDrafts({ ...drafts, [key]: e.target.value })} />}</AdminTd><AdminTd><AdminButton disabled={saving !== ""} busy={saving === key} onClick={() => void save(key)}>保存</AdminButton></AdminTd></tr>)}</tbody></AdminTable>}</AdminPage>;
}
