import { useCallback, useEffect, useState, type FormEvent } from "react";
import { adminCreateDatasource, adminListDatasources, adminPatchDatasource, adminTestDatasource, type AdminDatasource } from "../../api";
import { AdminDialog } from "../../components/AdminDialog";
import { AdminButton } from "../../components/AdminTable";
import { AdminInput, AdminNotice, AdminPage, AdminSelect, AdminTable, AdminTd, AdminTh, AdminTextarea } from "../../components/AdminTable";

const blank = { name: "", base_url: "", credential: "", whitelist: "", enabled: true };
function parseWhitelist(value: string) { if (!value.trim()) return []; try { const parsed = JSON.parse(value); if (Array.isArray(parsed) && parsed.every((item) => typeof item === "string")) return parsed; } catch { /* allow newline form below */ } return value.split(/[\n,]/).map((item) => item.trim()).filter(Boolean); }
export function DatasourcesPage() {
  const [items, setItems] = useState<AdminDatasource[]>([]); const [form, setForm] = useState(blank); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [testResult, setTestResult] = useState("");
  const load = useCallback(async () => { setLoading(true); try { setItems(await adminListDatasources()); } catch (e) { setError(e instanceof Error ? e.message : "数据源加载失败"); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const run = async (action: () => Promise<unknown>, ok: string) => { setBusy(true); setError(""); setSuccess(""); try { await action(); setSuccess(ok); await load(); } catch (e) { setError(e instanceof Error ? e.message : "操作失败"); } finally { setBusy(false); } };
  const create = async (event: FormEvent) => { event.preventDefault(); if (!form.base_url.startsWith("https://")) { setError("数据源地址必须使用 HTTPS"); return; } await run(async () => { await adminCreateDatasource({ name: form.name, type: "http_api", base_url: form.base_url, credential: form.credential, whitelist: parseWhitelist(form.whitelist), enabled: form.enabled }); setForm(blank); setOpen(false); }, "数据源已创建"); };
  return <AdminPage title="数据源管理" description="配置受白名单保护的 HTTP 数据源，凭据只在提交时发送。" actions={<AdminButton onClick={() => { setOpen(true); setError(""); }}>新建数据源</AdminButton>}>
    {success ? <AdminNotice kind="success">{success}</AdminNotice> : null}{error ? <AdminNotice>{error}</AdminNotice> : null}
    {loading ? <div className="rounded-xl border border-border bg-card p-8 text-center text-sm text-muted-fg">加载中…</div> : items.length === 0 ? <div className="rounded-xl border border-border bg-card p-8 text-center text-sm text-muted-fg">暂无数据源</div> : <AdminTable><thead><tr><AdminTh>名称</AdminTh><AdminTh>类型</AdminTh><AdminTh>Base URL</AdminTh><AdminTh>状态</AdminTh><AdminTh>操作</AdminTh></tr></thead><tbody>{items.map((item) => <tr key={item.id}><AdminTd className="font-medium">{item.name}</AdminTd><AdminTd>{item.type || "http_api"}</AdminTd><AdminTd className="max-w-sm truncate font-mono text-xs">{item.base_url}</AdminTd><AdminTd>{item.enabled ? "enabled" : "disabled"}</AdminTd><AdminTd><div className="flex flex-wrap gap-2"><button type="button" disabled={busy} onClick={() => void run(() => adminPatchDatasource(item.id, { enabled: !item.enabled }), "状态已更新")} className="text-xs text-primary hover:underline">{item.enabled ? "停用" : "启用"}</button><button type="button" disabled={busy} onClick={() => void adminTestDatasource(item.id).then((result) => setTestResult(result.ok ? "连接成功" : `连接失败${result.detail ? `：${result.detail}` : ""}`)).catch((e) => setError(e instanceof Error ? e.message : "测试失败"))} className="text-xs text-primary hover:underline">连通测试</button></div></AdminTd></tr>)}</tbody></AdminTable>}
    {testResult ? <AdminNotice kind="success">{testResult}</AdminNotice> : null}
    {open ? <AdminDialog title="新建数据源" onClose={() => setOpen(false)} onSubmit={create} busy={busy}><label className="block text-sm">名称<AdminInput required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label className="block text-sm">类型<AdminSelect className="w-full" value="http_api" disabled><option>http_api</option></AdminSelect></label><label className="block text-sm">Base URL<AdminInput required type="url" placeholder="https://example.internal" value={form.base_url} onChange={(e) => setForm({ ...form, base_url: e.target.value })} /></label><label className="block text-sm">Credential（不会回填或持久化）<AdminInput type="password" autoComplete="new-password" value={form.credential} onChange={(e) => setForm({ ...form, credential: e.target.value })} /></label><label className="block text-sm">Whitelist（JSON 数组或每行一个）<AdminTextarea rows={4} placeholder='["/api/v1"]' value={form.whitelist} onChange={(e) => setForm({ ...form, whitelist: e.target.value })} /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.enabled} onChange={(e) => setForm({ ...form, enabled: e.target.checked })} />启用</label></AdminDialog> : null}
  </AdminPage>;
}
