import { useCallback, useEffect, useState, type FormEvent } from "react";
import { adminCreateLlm, adminDefaultLlm, adminDeleteLlm, adminHealthLlm, adminListLlm, adminPatchLlm, type AdminLlmProvider } from "../../api";
import { AdminDialog } from "../../components/AdminDialog";
import { AdminButton, AdminInput, AdminNotice, AdminPage, AdminTable, AdminTd, AdminTh } from "../../components/AdminTable";

const blank = { name: "", vendor: "openai_compat", base_url: "", api_key: "", models: "", default_model: "" };

export function LlmPage() {
  const [items, setItems] = useState<AdminLlmProvider[]>([]);
  const [defaultProvider, setDefaultProvider] = useState<AdminLlmProvider | null>(null);
  const [form, setForm] = useState(blank); const [editing, setEditing] = useState<AdminLlmProvider | null>(null);
  const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [health, setHealth] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const [providers, currentDefault] = await Promise.all([adminListLlm(), adminDefaultLlm()]); setItems(providers); setDefaultProvider(currentDefault); } catch (e) { setError(e instanceof Error ? e.message : "LLM provider 加载失败"); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const run = async (action: () => Promise<unknown>, ok: string) => { setBusy(true); setError(""); setSuccess(""); try { await action(); setSuccess(ok); await load(); } catch (e) { setError(e instanceof Error ? e.message : "操作失败"); } finally { setBusy(false); } };
  const openCreate = () => { setEditing(null); setForm(blank); setOpen(true); setError(""); };
  const openEdit = (item: AdminLlmProvider) => { setEditing(item); setForm({ name: item.name, vendor: item.vendor || "openai_compat", base_url: item.base_url, api_key: "", models: item.models.join(", "), default_model: item.default_model }); setOpen(true); setError(""); };
  const save = async (event: FormEvent) => { event.preventDefault(); const body = { name: form.name, vendor: form.vendor, base_url: form.base_url, api_key: form.api_key, models: form.models.split(",").map((model) => model.trim()).filter(Boolean), default_model: form.default_model }; await run(() => editing ? adminPatchLlm(editing.id, { ...body, ...(form.api_key ? { api_key: form.api_key } : {}) }) : adminCreateLlm(body), editing ? "provider 已更新" : "provider 已创建"); setForm(blank); setEditing(null); setOpen(false); };
  const healthCheck = async (id: string) => { try { const result = await adminHealthLlm(id); setHealth(result.ok ? "健康检查通过" : `健康检查失败${result.detail ? `：${result.detail}` : ""}`); } catch (e) { setError(e instanceof Error ? e.message : "健康检查失败"); } };
  return <AdminPage title="LLM Provider" description="管理模型供应商。API key 仅通过密码控件提交，列表永不显示明文。" actions={<AdminButton onClick={openCreate}>新增 Provider</AdminButton>}>
    {success ? <AdminNotice kind="success">{success}</AdminNotice> : null}{error ? <AdminNotice>{error}</AdminNotice> : null}
    <div className="rounded-xl border border-border bg-card p-4 text-sm shadow-panel">当前默认 Provider：<span className="font-medium">{defaultProvider?.name || "未设置"}</span></div>
    {loading ? <div className="rounded-xl border border-border bg-card p-8 text-center text-sm text-muted-fg">加载中…</div> : items.length === 0 ? <div className="rounded-xl border border-border bg-card p-8 text-center text-sm text-muted-fg">暂无 Provider</div> : <AdminTable><thead><tr><AdminTh>名称</AdminTh><AdminTh>Vendor</AdminTh><AdminTh>Base URL</AdminTh><AdminTh>Models</AdminTh><AdminTh>默认模型</AdminTh><AdminTh>状态</AdminTh><AdminTh>操作</AdminTh></tr></thead><tbody>{items.map((item) => <tr key={item.id}><AdminTd className="font-medium">{item.name}</AdminTd><AdminTd>{item.vendor || "—"}</AdminTd><AdminTd className="max-w-xs truncate font-mono text-xs">{item.base_url}</AdminTd><AdminTd className="max-w-xs truncate text-xs">{item.models.join(", ") || "—"}</AdminTd><AdminTd>{item.default_model || "—"}</AdminTd><AdminTd>{item.status || item.api_key_encrypted || "configured"}</AdminTd><AdminTd><div className="flex flex-wrap gap-2"><button type="button" disabled={busy} onClick={() => openEdit(item)} className="text-xs text-primary hover:underline">编辑</button><button type="button" disabled={busy} onClick={() => void healthCheck(item.id)} className="text-xs text-primary hover:underline">Health</button><button type="button" disabled={busy} onClick={() => { if (window.confirm(`确认删除 ${item.name}？`)) void run(() => adminDeleteLlm(item.id), "Provider 已删除"); }} className="text-xs text-destructive hover:underline">删除</button></div></AdminTd></tr>)}</tbody></AdminTable>}
    {health ? <AdminNotice kind="success">{health}</AdminNotice> : null}
    {open ? <AdminDialog title={editing ? "编辑 Provider" : "新增 Provider"} onClose={() => { setOpen(false); setEditing(null); setForm(blank); }} onSubmit={save} busy={busy}><label className="block text-sm">名称<AdminInput required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label className="block text-sm">Vendor<AdminInput value={form.vendor} onChange={(e) => setForm({ ...form, vendor: e.target.value })} /></label><label className="block text-sm">Base URL<AdminInput required type="url" value={form.base_url} onChange={(e) => setForm({ ...form, base_url: e.target.value })} /></label><label className="block text-sm">API key（不会回填或持久化）<AdminInput type="password" autoComplete="new-password" value={form.api_key} onChange={(e) => setForm({ ...form, api_key: e.target.value })} /></label><label className="block text-sm">Models（逗号分隔）<AdminInput value={form.models} onChange={(e) => setForm({ ...form, models: e.target.value })} /></label><label className="block text-sm">默认模型<AdminInput value={form.default_model} onChange={(e) => setForm({ ...form, default_model: e.target.value })} /></label></AdminDialog> : null}
  </AdminPage>;
}
