import { useCallback, useEffect, useState, type FormEvent } from "react";
import { adminCreateTool, adminDeleteTool, adminListTools, adminPatchTool, adminTestTool, type AdminTool } from "../../api";
import { AdminDialog } from "../../components/AdminDialog";
import { AdminButton, AdminInput, AdminNotice, AdminPage, AdminTable, AdminTd, AdminTextarea, AdminTh } from "../../components/AdminTable";

const blank = { name: "", description: "", input_schema: "{}", output_schema: "{}", execution: "{}", scenario_id: "" };
function parseJson(text: string, label: string) { try { return JSON.parse(text) as Record<string, unknown>; } catch { throw new Error(`${label} 必须是合法 JSON`); } }
export function ToolsPage() {
  const [items, setItems] = useState<AdminTool[]>([]); const [form, setForm] = useState(blank); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [testResult, setTestResult] = useState("");
  const load = useCallback(async () => { setLoading(true); try { setItems(await adminListTools()); } catch (e) { setError(e instanceof Error ? e.message : "工具加载失败"); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const run = async (action: () => Promise<unknown>, ok: string) => { setBusy(true); setError(""); setSuccess(""); try { await action(); setSuccess(ok); await load(); } catch (e) { setError(e instanceof Error ? e.message : "操作失败"); } finally { setBusy(false); } };
  const create = async (event: FormEvent) => { event.preventDefault(); if (!/^[a-z][a-z0-9_]{1,63}$/.test(form.name)) { setError("工具名必须匹配 /^[a-z][a-z0-9_]{1,63}$/"); return; } try { const body = { name: form.name, description: form.description, input_schema: parseJson(form.input_schema, "input_schema"), output_schema: parseJson(form.output_schema, "output_schema"), execution: parseJson(form.execution, "execution"), ...(form.scenario_id ? { scenario_id: form.scenario_id } : {}) }; await run(() => adminCreateTool(body), "工具已创建"); setOpen(false); setForm(blank); } catch (e) { setError(e instanceof Error ? e.message : "表单校验失败"); } };
  return <AdminPage title="工具管理" description="维护能力工具状态与执行配置。" actions={<AdminButton onClick={() => { setOpen(true); setError(""); }} >新建工具</AdminButton>}>
    {success ? <AdminNotice kind="success">{success}</AdminNotice> : null}{error ? <AdminNotice>{error}</AdminNotice> : null}
    {loading ? <div className="rounded-xl border border-border bg-card p-8 text-center text-sm text-muted-fg">加载中…</div> : items.length === 0 ? <div className="rounded-xl border border-border bg-card p-8 text-center text-sm text-muted-fg">暂无工具</div> : <AdminTable><thead><tr><AdminTh>名称</AdminTh><AdminTh>状态</AdminTh><AdminTh>描述</AdminTh><AdminTh>执行配置</AdminTh><AdminTh>操作</AdminTh></tr></thead><tbody>{items.map((item) => <tr key={item.id}><AdminTd><span className="font-mono text-xs">{item.name}</span></AdminTd><AdminTd><AdminButton variant="secondary" busy={busy} onClick={() => void run(() => adminPatchTool(item.id, { status: item.status === "enabled" ? "disabled" : "enabled" }), "状态已更新")}>{item.status || "unknown"}</AdminButton></AdminTd><AdminTd>{item.description || "—"}</AdminTd><AdminTd className="text-xs text-muted-fg">{item.execution ? `${Object.keys(item.execution).length} 个配置项` : "—"}</AdminTd><AdminTd><div className="flex flex-wrap gap-2"><button type="button" disabled={busy} onClick={() => void adminTestTool(item.id).then((result) => setTestResult(JSON.stringify(result))).catch((e) => setError(e instanceof Error ? e.message : "测试失败"))} className="text-xs text-primary hover:underline">测试</button><button type="button" disabled={busy} onClick={() => { if (window.confirm(`确认删除 ${item.name}？`)) void run(() => adminDeleteTool(item.id), "工具已删除"); }} className="text-xs text-destructive hover:underline">删除</button></div></AdminTd></tr>)}</tbody></AdminTable>}
    {testResult ? <AdminNotice kind="success">测试结果：{testResult}</AdminNotice> : null}
    {open ? <AdminDialog title="新建工具" onClose={() => setOpen(false)} onSubmit={create} busy={busy}><label className="block text-sm">名称<AdminInput required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label className="block text-sm">描述<AdminInput value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><label className="block text-sm">input_schema<AdminTextarea rows={5} value={form.input_schema} onChange={(e) => setForm({ ...form, input_schema: e.target.value })} /></label><label className="block text-sm">output_schema<AdminTextarea rows={5} value={form.output_schema} onChange={(e) => setForm({ ...form, output_schema: e.target.value })} /></label><label className="block text-sm">execution<AdminTextarea rows={5} value={form.execution} onChange={(e) => setForm({ ...form, execution: e.target.value })} /></label><label className="block text-sm">scenario_id（可选）<AdminInput value={form.scenario_id} onChange={(e) => setForm({ ...form, scenario_id: e.target.value })} /></label></AdminDialog> : null}
  </AdminPage>;
}
